### ISSUE TITLE
adding text to map

### ISSUE THREAD

**Issue by zeitos** [leonawicz/mapmate#2]
Hi, is there a way to add a text to each frame?

**Comment by leonawicz** [comment]
Not at the moment, but I've done this in the past and would like to include this. But it opens other questions. For example, do I add more arguments for also allowing the positioning or color or other text attributes to change across the sequence of maps as well? Ideally I'd allow users to specify everything  but it could become cumbersome quickly. I think the first thing I would do is add in options to pass specific text through to `ggplot2` functions like `ggtitle` and `labs`. I will look into this for sure. It's a good idea.

Since this is the first Github issue expressing a legit feature request, I'll just add some more background info about the direction/vision I have for the package in general.

The assumed/intended context for package use is for generating still image sequences to be subsequently loaded onto a timeline in a dedicated video editing program outside of R. For that reason, I see some things as being conveniently done at that later stage and offering more freedom for the user. If I want to add a title, I just do it in the video editor. I might use the frames from R for more than one project/video and typically won't want words baked into the image files themselves. On the other hand, if I'm including a counter of some sort tabulates some kind of map data and that varies across frames, I may want to draw that in R using the source data so that it is spread over an image sequence that matches up with my maps (though I still might make it a separate text layer- i.e. a set of blank "maps" with text only, for the layering freedom.) In general, the more plot elements you have on top of each other baked into the original png files output by R, the more limited you are later being unable to adjust content layers during video editing. 

I know the functionality and options will expand, but I have to be careful about how I do so to avoid making it too complex. Ideally I would love to give `save_map` the flexibility to make any kind of map with any kind of projection or positioning or orientation with any kind of data plotted on it any any form that ggplot can handle including use of grouping variables by different colors and facetting with multiple panels of different maps or globes... and so on. But the strength of the package is in providing some convenience for batch image generation for certain types of maps. Attempting to expose all the functionality of `ggplot2` to the user would be overkill. All the `save_map` function really does is wrap up a handful of very specific `ggplot2` calls (which could easily be pulled out of the source code and adapted and customized for specific use cases that don't fit). The more complex I make it, the more it will become a really ugly and confusing detailed interface to `ggplot2` itself, which I want to avoid. There is a happy medium somewhere. As I continue to work on this project I'm open to any ideas about the best way to refactor the code as it develops.

Basically all it does is (1) require data frames in certain format with certain contents, (2) give only two map options: use a flat world map or call `coord_map` with the orthographic projection to make a globe, (3) use specific geoms, given the data and the user settings, (4) use a custom ggplot2 theme that effectively removes all the axes and text and expands the plotting region to the full device window, and (5) save pngs with transparent backgrounds so future layering of the saved images is possible. It's a pretty specific set of things that it does. I would like to add as much user control over exactly what `ggplot2` does internally with the data as possible, but I have to do so carefully without ruining the basic purpose of `mapmate`.

Ultimately, as long as a user has the kind of data that can be plotted as a series of varying plots, in a way that would make sense to display as an animation, there's no reason they can't just put it in a loop or use `purrr::walk` to loop over their data, plotting and saving as they go. And that is one reason for me not to bother trying to make `mapmate` offer every nuanced possibility in terms of using `ggplot2` to make graphs or maps. I would like to include everything that I and others think "makes sense" to include, without trying to add so much that it becomes unfocused and difficult to use. That's a fine line sometimes and not everyone draws that line in the same place, so I welcome input and suggestions about additional options or refactoring of approaches used from anyone who wants to contribute.
