### ISSUE TITLE
utilizing ffmpeg

### ISSUE THREAD

**Issue by dcasciotti** [leonawicz/mapmate#3]
Greetings
This is a great app.
I have been trying to use ffmpeg to knit three  bathymetry sequences and not having success.
Have you considered using ffmpeg?

Thanks
Dave Casciotti

**Comment by leonawicz** [comment]
Hi Dave,

I'm not very familiar with ffmpeg. The only R package I know of that offers a wrapper around it is `animation`. See the help docs for `saveVideo` in that package if you haven't already tried that. In the notes the author also mentions limited knowledge of ffmpeg. I haven't used `animation` recently but I am thinking a user could come up against insufficient flexibility and available options when trying to use ffmpeg via `saveVideo`.

Although `mapmate` is aimed toward users who want to dump their image sequence output PNGs onto a dedicated GUI-based video editing program's timeline for final editing and rendering tweaks, I can see strong benefit in including in `mapmate` a `ffmpeg` wrapper function which simply translates a user's arguments into a system call to ffmpeg. The user could provide the specifications they need to using a familiar R syntax that is their comfort zone and the function `ffmpeg` would just translate and arrange those arguments into the appropriate character string to pass to `system` for example.

Such a function would be great to include in `mapmate` because unlike packages such as `animation`, which aim, appropriately, to provide the ability to create animations as directly and seamlessly as possible, `mapmate` remains focused on generating the raw still image sequences and leaving the user with the power to do what they want with those sequences secondarily. Having a solid and thorough wrapper function to ffmpeg would provide an option that represents a complete alternative to the otherwise assumed GUI-based post-processing environment. It would be especially handy for Linux users, which the package favors in its current state of development (if taking advantage of heavy parallel processing), allowing them to call `ffmpeg` right after `save_map` for example, doing their entire job of plotting and rendering in a single R session on a server. I could see people using the package on existing image sequences not made by `mapmate` just for the convenience and control and ability to do it from R.

I've looked around but haven't found anything that already does this. I too am not up to speed with ffmpeg. I've used it in the past a literal few times, with more failure than success. Writing a `ffmpeg` wrapper function, however, presumes expertise in what I'm wrapping of course. So I would have to dig back into it and practice using ffmpeg a bit before I could integrate a wrapper into the package. It's not a priority for development (right now I'm focused on finally getting the `networks`-related map type functions incorporated into the package among other features) but I would absolutely love to include it. I can't say when it will happen, but I can say I won't close this issue until `mapmate` includes an `ffmpeg` function. It sounds too handy to exclude.

Matt

**Comment by leonawicz** [comment]
Also, on looking at the source code for `saveVideo` in `animation`, I'm unfamiliar enough with ffmpeg that I cannot immediately tell if the `other.opts` argument offers the user true flexibility, or if there is still some rigidity in controlling ffmpeg given the overall string that is composed. It's probably still the best option at least until a dedicated `ffmpeg` wrapper can be written.

**Comment by leonawicz** [comment]
@dcasciotti Good news, the next minor package version update will include a wrapper function, `ffmpeg`, for convenient rendering of existing still image sequences. It's all I'm adding this update so it won't take long to get the update on Github. I'm still working on the function and doing testing, but so far it is working very well.

Matt

**Comment by dcasciotti** [comment]
Matt
This is really fantastic news.  This feature will benefit a wide range of users and facilitate  many applications and interesting examples from many disciplines.
Dave

**Comment by leonawicz** [comment]
@dcasciotti Hi Dave, I have released v0.2.1, which adds the `ffmpeg` wrapper function. It should work fine for very basic uses. For more complex usage like merging and layering multiple image sequences into a single video, it does not work well.

Nevertheless, the function represents a good template from which to continue working on it if you or anyone else with more FFmpeg experience has interest in adding code to it to help translate R syntax for some of the more esoteric and complex FFmpeg statements.

Also, I have only tested it under Windows so far. While behavior shouldn't be different under Linux, there are some Linux-related options I haven't actually tested out yet, such as the use of globbing for file names. Try to use it only in Windows for now, unless you are inclined to do additional testing.

Here is a [tutorial and discussion of current limitations](https://leonawicz.github.io/mapmate/ffmpeg.html)

Matt

**Comment by dcasciotti** [comment]
Hi Matt,


I worked through the complete tutorial on my MBP running Sierra 10.12 and everything works great, I rejoined the ffmpeg user group after a couple years hiatus looking for ways to overlay sequences with ffmpeg. 
The group is extremely active.
In looking through your data i noticed bathymetry data.  I am interested in applying 3d bathymetry data with ocean tracer samples , http://leafletmaps.webmappingevents.com/nitrate3D.html <http://leafletmaps.webmappingevents.com/nitrate3D.html>, on the globe. Are the globe boundaries WGS 84?

Dave

**Comment by leonawicz** [comment]
Hi Dave,

Yes. the globe view in my package is a projection using `ggplot2::coord_map` with the argument `projection="ortho"`, but the bathymetry map dataset used in the examples begins as WGS84 with an exact extent of longitude `[-180, 180]` and latitude `[-90, 90]` (coordinates in the `bathymetry` table are cell centroids). I began with a 10-minute resolution download via the `marmap` package, but then aggregated lon and lat by a factor of 20 for package examples:

https://github.com/leonawicz/mapmate/blob/master/data-raw/rawdata.R

I began with an already downloaded file, so the code above doesn't make direct use of `marmap`, only it's product, but I recall it being very easy to download bathymetry maps of different extents and resolutions via that package.

Glad to hear everything is working for you. I hope the ffmpeg user group proves fruitful.

Thanks,
Matt
